//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.16 at 10:48:33 AM EET 
//


package org.opendelos.legacydomain.institution;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StaffMemberId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StaffMemberUId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StaffMemberName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AltName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Affiliation" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PreferredLicense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Image" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Link" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://gunet.gr/Institution}StaffMemberCourses" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StaffPreferences" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Record" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Broadcast" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Access" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Publish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "staffMemberId",
    "staffMemberUid",
    "staffMemberName",
    "altName",
    "email",
    "affiliation",
    "preferredLicense",
    "image",
    "link",
    "staffMemberCourses",
    "staffPreferences"
})
@XmlRootElement(name = "StaffMember")
public class StaffMember {

    @XmlElement(name = "StaffMemberId", required = true)
    protected String staffMemberId;
    @XmlElement(name = "StaffMemberUid", required = true)
    protected String staffMemberUid;
    @XmlElement(name = "StaffMemberName", required = true)
    protected String staffMemberName;
    @XmlElement(name = "AltName")
    protected String altName;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "Affiliation")
    protected List<String> affiliation;
    @XmlElement(name = "PreferredLicense")
    protected String preferredLicense;
    @XmlElement(name = "Image")
    protected String image;
    @XmlElement(name = "Link")
    protected String link;
    @XmlElement(name = "StaffMemberCourses")
    protected List<StaffMemberCourses> staffMemberCourses;
    @XmlElement(name = "StaffPreferences")
    protected StaffPreferences staffPreferences;

    /**
     * Gets the value of the sId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSId() {
        return staffMemberId;
    }

    /**
     * Sets the value of the sId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSId(String value) {
        this.staffMemberId = value;
    }

    /**
     * Gets the value of the uId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUId() {
        return staffMemberUid;
    }

    /**
     * Sets the value of the uId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUId(String value) {
        this.staffMemberUid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return staffMemberName;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.staffMemberName = value;
    }

    /**
     * Gets the value of the altName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltName() {
        return altName;
    }

    /**
     * Sets the value of the altName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltName(String value) {
        this.altName = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the affiliation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAffiliation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAffiliation() {
        if (affiliation == null) {
            affiliation = new ArrayList<String>();
        }
        return this.affiliation;
    }

    /**
     * Gets the value of the preferredLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredLicense() {
        return preferredLicense;
    }

    /**
     * Sets the value of the preferredLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredLicense(String value) {
        this.preferredLicense = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the staffMemberCourses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the staffMemberCourses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStaffMemberCourses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StaffMemberCourses }
     * 
     * 
     */
    public List<StaffMemberCourses> getStaffMemberCourses() {
        if (staffMemberCourses == null) {
            staffMemberCourses = new ArrayList<StaffMemberCourses>();
        }
        return this.staffMemberCourses;
    }

    /**
     * Gets the value of the staffPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link StaffPreferences }
     *     
     */
    public StaffPreferences getStaffPreferences() {
        return staffPreferences;
    }

    /**
     * Sets the value of the staffPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffPreferences }
     *     
     */
    public void setStaffPreferences(StaffPreferences value) {
        this.staffPreferences = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Record" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Broadcast" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Access" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Publish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "record",
        "broadcast",
        "access",
        "publish"
    })
    public static class StaffPreferences {

        @XmlElement(name = "Record")
        protected String record;
        @XmlElement(name = "Broadcast")
        protected String broadcast;
        @XmlElement(name = "Access")
        protected String access;
        @XmlElement(name = "Publish")
        protected String publish;

        /**
         * Gets the value of the record property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecord() {
            return record;
        }

        /**
         * Sets the value of the record property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecord(String value) {
            this.record = value;
        }

        /**
         * Gets the value of the broadcast property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBroadcast() {
            return broadcast;
        }

        /**
         * Sets the value of the broadcast property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBroadcast(String value) {
            this.broadcast = value;
        }

        /**
         * Gets the value of the access property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccess() {
            return access;
        }

        /**
         * Sets the value of the access property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccess(String value) {
            this.access = value;
        }

        /**
         * Gets the value of the publish property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPublish() {
            return publish;
        }

        /**
         * Sets the value of the publish property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPublish(String value) {
            this.publish = value;
        }

    }

}
