//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.16 at 10:48:33 AM EET 
//


package org.opendelos.model.structure;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import lombok.Getter;
import lombok.Setter;
import org.opendelos.model.dates.CustomPeriod;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.IndexDirection;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "StudyPrograms")
@Getter
@Setter
public class StudyProgram implements Serializable {

	@Id
	protected String id;
	@Indexed(direction = IndexDirection.ASCENDING)
    protected String identity;
    protected String title;
    protected String departmentId;
	protected String schoolId;
	protected String study;
	private List<CustomPeriod> customPeriods;

	public List<CustomPeriod> getCustomPeriods() {
		if (customPeriods == null) {
			customPeriods = new ArrayList<>();
		}
		return customPeriods;
	}
}
