//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 10:09:14 AM EEST 
//


package org.opendelos.legacydomain.videolecture;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CodeSourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="internal"/>
 *     &lt;enumeration value="programme_studies"/>
 *     &lt;enumeration value="programme_studies"/>
 *     &lt;enumeration value="secretariat"/>
 *     &lt;enumeration value="lms"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CodeSourceType")
@XmlEnum
public enum CodeSourceType {

    internal,
    programme_studies,
    secretariat,
    lms,
    other;

    public String value() {
        return name();
    }

    public static CodeSourceType fromValue(String v) {
        return valueOf(v);
    }

}
