//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 10:09:14 AM EEST 
//


package org.opendelos.legacydomain.videolecture;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gunet.dilosdlm.domain.videolecture package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gunet.dilosdlm.domain.videolecture
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VideoLecture }
     * 
     */
    public VideoLecture createVideoLecture() {
        return new VideoLecture();
    }

    /**
     * Create an instance of {@link CourseType }
     * 
     */
    public CourseType createCourseType() {
        return new CourseType();
    }

    /**
     * Create an instance of {@link LinkedType }
     * 
     */
    public LinkedType createLinkedType() {
        return new LinkedType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link VideoLecture.Presentation }
     * 
     */
    public VideoLecture.Presentation createVideoLecturePresentation() {
        return new VideoLecture.Presentation();
    }

    /**
     * Create an instance of {@link VideoLecture.Subs }
     * 
     */
    public VideoLecture.Subs createVideoLectureSubs() {
        return new VideoLecture.Subs();
    }

    /**
     * Create an instance of {@link VideoLecture.References }
     * 
     */
    public VideoLecture.References createVideoLectureReferences() {
        return new VideoLecture.References();
    }

    /**
     * Create an instance of {@link SortOrderType }
     * 
     */
    public SortOrderType createSortOrderType() {
        return new SortOrderType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link ClassroomType }
     * 
     */
    public ClassroomType createClassroomType() {
        return new ClassroomType();
    }

    /**
     * Create an instance of {@link VideoLecture.Access }
     * 
     */
    public VideoLecture.Access createVideoLectureAccess() {
        return new VideoLecture.Access();
    }

    /**
     * Create an instance of {@link VideoLecture.Rights }
     * 
     */
    public VideoLecture.Rights createVideoLectureRights() {
        return new VideoLecture.Rights();
    }

    /**
     * Create an instance of {@link VideoLecture.Licenses }
     * 
     */
    public VideoLecture.Licenses createVideoLectureLicenses() {
        return new VideoLecture.Licenses();
    }

    /**
     * Create an instance of {@link VideoLecture.PlayerOptions }
     * 
     */
    public VideoLecture.PlayerOptions createVideoLecturePlayerOptions() {
        return new VideoLecture.PlayerOptions();
    }

    /**
     * Create an instance of {@link VideoLecture.Relation }
     * 
     */
    public VideoLecture.Relation createVideoLectureRelation() {
        return new VideoLecture.Relation();
    }

    /**
     * Create an instance of {@link VideoLecture.Clips }
     * 
     */
    public VideoLecture.Clips createVideoLectureClips() {
        return new VideoLecture.Clips();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link AccessPropertiesType }
     * 
     */
    public AccessPropertiesType createAccessPropertiesType() {
        return new AccessPropertiesType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link UrlLinkType }
     * 
     */
    public UrlLinkType createUrlLinkType() {
        return new UrlLinkType();
    }

    /**
     * Create an instance of {@link ResponsibleUnitType }
     * 
     */
    public ResponsibleUnitType createResponsibleUnitType() {
        return new ResponsibleUnitType();
    }

    /**
     * Create an instance of {@link CourseType.CourseId }
     * 
     */
    public CourseType.CourseId createCourseTypeCourseId() {
        return new CourseType.CourseId();
    }

    /**
     * Create an instance of {@link LinkedType.Path }
     * 
     */
    public LinkedType.Path createLinkedTypePath() {
        return new LinkedType.Path();
    }

    /**
     * Create an instance of {@link StatusType.StatusProperty }
     * 
     */
    public StatusType.StatusProperty createStatusTypeStatusProperty() {
        return new StatusType.StatusProperty();
    }

    /**
     * Create an instance of {@link VideoLecture.Presentation.FileName }
     * 
     */
    public VideoLecture.Presentation.FileName createVideoLecturePresentationFileName() {
        return new VideoLecture.Presentation.FileName();
    }

    /**
     * Create an instance of {@link VideoLecture.Subs.Sub }
     * 
     */
    public VideoLecture.Subs.Sub createVideoLectureSubsSub() {
        return new VideoLecture.Subs.Sub();
    }

    /**
     * Create an instance of {@link VideoLecture.References.Reference }
     * 
     */
    public VideoLecture.References.Reference createVideoLectureReferencesReference() {
        return new VideoLecture.References.Reference();
    }

}
