//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 09:28:23 AM EEST 
//
/**
 * Implementation of StaffList XSD Schema
 * <p>
 * @author openDelos Team
 * @since 0.1
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://gunet.gr/StaffList", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opendelos.legacydomain.stafflist;
