//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 02:16:25 PM EET 
//
/**
 * Implementation of Presentation XSD Schema
 * <p>
 * @author openDelos Team
 * @since 0.1
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://gunet.gr/Presentation")
package org.opendelos.legacydomain.presentation;
