//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 10:49:25 AM EET 
//


package org.opendelos.model.calendar;

import lombok.Getter;
import lombok.Setter;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.IndexDirection;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "AcademicCalendar")
@Getter
@Setter
public class AcademicCalendar implements java.io.Serializable {

    @Id
    protected String id;
    @Indexed(direction = IndexDirection.ASCENDING)
    protected String year;
    protected String enabled;
    protected Institution institution;

}
