//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.24 at 12:52:31 PM EEST 
//


package org.opendelos.legacydomain.dlmusers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.opendelos.legacydomain.dlmuser.DlmUser;


/**
 * <p>Java class for UsersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://gunet.gr/DlmUser}DlmUser"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsersType", propOrder = {
    "userID",
    "dlmUser"
})
public class UsersType {

    @XmlElement(name = "UserID", required = true)
    protected String userID;
    @XmlElement(name = "DlmUser", namespace = "http://gunet.gr/DlmUser", required = true)
    protected DlmUser dlmUser;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the dlmUser property.
     * 
     * @return
     *     possible object is
     *     {@link DlmUser }
     *     
     */
    public DlmUser getDlmUser() {
        return dlmUser;
    }

    /**
     * Sets the value of the dlmUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link DlmUser }
     *     
     */
    public void setDlmUser(DlmUser value) {
        this.dlmUser = value;
    }

}
