//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.30 at 10:16:19 AM EET 
//


package org.opendelos.legacydomain.queryresponse;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumofResults" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MediaBasePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlayerBasePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Resources" type="{http://gunet.gr/QueryResponse}ResourcesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numofResults",
    "mediaBasePath",
    "playerBasePath",
    "resources"
})
@XmlRootElement(name = "QueryResponse")
@Component
@Scope(value="session", proxyMode=ScopedProxyMode.TARGET_CLASS)
public class QueryResponse {

    @XmlElement(name = "NumofResults")
    protected int numofResults;
    @XmlElement(name = "MediaBasePath")
    protected String mediaBasePath;
    @XmlElement(name = "PlayerBasePath")
    protected String playerBasePath;
    @XmlElement(name = "Resources")
    protected List<ResourcesType> resources;

    /**
     * Gets the value of the numofResults property.
     * 
     */
    public int getNumofResults() {
        return numofResults;
    }

    /**
     * Sets the value of the numofResults property.
     * 
     */
    public void setNumofResults(int value) {
        this.numofResults = value;
    }

    /**
     * Gets the value of the mediaBasePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaBasePath() {
        return mediaBasePath;
    }

    /**
     * Sets the value of the mediaBasePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaBasePath(String value) {
        this.mediaBasePath = value;
    }

    /**
     * Gets the value of the playerBasePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerBasePath() {
        return playerBasePath;
    }

    /**
     * Sets the value of the playerBasePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerBasePath(String value) {
        this.playerBasePath = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resources property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResources().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourcesType }
     * 
     * 
     */
    public List<ResourcesType> getResources() {
        if (resources == null) {
            resources = new ArrayList<ResourcesType>();
        }
        return this.resources;
    }

}
