//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.30 at 10:16:19 AM EET 
//


package org.opendelos.legacydomain.queryresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.opendelos.legacydomain.presentation.Presentation;
import org.opendelos.legacydomain.videolecture.VideoLecture;


/**
 * <p>Java class for ResourcesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourcesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://gunet.gr/VideoLecture}VideoLecture"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourcesType", propOrder = {
    "resourceID",
    "videoLecture",
    "presentation"
})
public class ResourcesType {

    @XmlElement(name = "ResourceID", required = true)
    protected String resourceID;
    @XmlElement(name = "VideoLecture", namespace = "http://gunet.gr/VideoLecture", required = true)
    protected VideoLecture videoLecture;
    @XmlElement(name = "Presentation", namespace = "http://gunet.gr/Presentation", required = false)
    protected Presentation presentation;
    /**
     * Gets the value of the resourceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceID() {
        return resourceID;
    }

    /**
     * Sets the value of the resourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceID(String value) {
        this.resourceID = value;
    }

    /**
     * Gets the value of the videoLecture property.
     * 
     * @return
     *     possible object is
     *     {@link VideoLecture }
     *     
     */
    public VideoLecture getVideoLecture() {
        return videoLecture;
    }

    /**
     * Sets the value of the videoLecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoLecture }
     *     
     */
    public void setVideoLecture(VideoLecture value) {
        this.videoLecture = value;
    }

    public Presentation getPresentation() {
        return presentation;
    }

    public void setPresentation(Presentation presentation) {
        this.presentation = presentation;
    }
}
