//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 01:45:35 PM EEST 
//


package org.opendelos.legacydomain.scheduler;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalendarType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalendarType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://gunet.gr/DsmCalendarXml}DsmCalendarXml"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalendarType", propOrder = {
    "resourceID",
    "dsmCalendarXml"
})
public class CalendarType implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(name = "ResourceID", required = true)
    protected String resourceID;
    @XmlElement(name = "DsmCalendarXml", namespace = "http://gunet.gr/DsmCalendarXml", required = true)
    protected DsmCalendarXml dsmCalendarXml;

    /**
     * Gets the value of the resourceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceID() {
        return resourceID;
    }

    /**
     * Sets the value of the resourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceID(String value) {
        this.resourceID = value;
    }

    /**
     * Gets the value of the dsmCalendarXml property.
     * 
     * @return
     *     possible object is
     *     {@link DsmCalendarXml }
     *     
     */
    public DsmCalendarXml getDsmCalendarXml() {
        return dsmCalendarXml;
    }

    /**
     * Sets the value of the dsmCalendarXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link DsmCalendarXml }
     *     
     */
    public void setDsmCalendarXml(DsmCalendarXml value) {
        this.dsmCalendarXml = value;
    }

}
