//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.16 at 09:23:23 AM EEST 
//


package org.opendelos.legacydomain.scheduler;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gunet.dilosdsm.domain.xml.DsmCalendarXml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gunet.dilosdsm.domain.xml.DsmCalendarXml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.opendelos.legacydomain.scheduler.DsmCalendarXml }
     * 
     */
    public org.opendelos.legacydomain.scheduler.DsmCalendarXml createDsmCalendarXml() {
        return new org.opendelos.legacydomain.scheduler.DsmCalendarXml();
    }

}
