//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.19 at 12:51:15 PM EEST 
//


package org.opendelos.eventsapp.services.upload.analyzers;

import java.util.ArrayList;
import java.util.List;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class RecorderSlideShow {

    protected String date;
    protected String nowtime;
    protected Slides slides;

    @Getter
    @Setter
    public static class Slides {

        protected String description;
        protected List<Slide> slide;

        public List<Slide> getSlide() {
            if (slide == null) {
                slide = new ArrayList<>();
            }
            return this.slide;
        }

        @Getter
        @Setter
        public static class Slide {

            protected String title;
            protected String url;
            protected String time;

        }

    }

}
