//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.26 at 08:17:33 AM EET 
//
/**
 * Implementation of Cuts XSD Schema
 * <p>
 * @author openDelos Team
 * @since 0.1
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://gunet.gr/Cuts")
package org.opendelos.legacydomain.cuts;
