//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 11:02:19 AM EEST 
//


package org.opendelos.legacydomain.dlmuser;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Uid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Sid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Affiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Institution" type="{http://gunet.gr/DlmUser}UnitType" minOccurs="0"/>
 *         &lt;element name="Department" type="{http://gunet.gr/DlmUser}UnitType" minOccurs="0"/>
 *         &lt;element name="UserRights" type="{http://gunet.gr/DlmUser}UserRightsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SsoAttributes" type="{http://gunet.gr/DlmUser}SsoAttributesType" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResetCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PassPhrase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tokens" type="{http://gunet.gr/DlmUser}UserTokens" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LastVisit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "uid",
    "sid",
    "email",
    "password",
    "affiliation",
    "institution",
    "department",
    "userRights",
    "ssoAttributes",
    "status",
    "resetCode",
    "passPhrase",
    "userType",
    "tokens",
    "lastVisit"
})
@XmlRootElement(name = "DlmUser")
public class DlmUser  implements java.io.Serializable  {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4504301338283221639L;
	@XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Uid")
    protected String uid;
    @XmlElement(name = "Sid", required = true)
    protected String sid;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "Password")
    protected String password;
    @XmlElement(name = "Affiliation")
    protected String affiliation;
    @XmlElement(name = "Institution")
    protected UnitType institution;
    @XmlElement(name = "Department")
    protected UnitType department;
    @XmlElement(name = "UserRights")
    protected List<UserRightsType> userRights;
    @XmlElement(name = "SsoAttributes")
    protected SsoAttributesType ssoAttributes;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "ResetCode")
    protected String resetCode;
    @XmlElement(name = "PassPhrase")
    protected String passPhrase;
    @XmlElement(name = "UserType")
    protected String userType;
    @XmlElement(name = "Tokens")
    protected List<UserTokens> tokens;
    @XmlElement(name = "LastVisit")
    protected String lastVisit;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the sid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSid(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliation() {
        return affiliation;
    }

    /**
     * Sets the value of the affiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliation(String value) {
        this.affiliation = value;
    }

    /**
     * Gets the value of the institution property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType }
     *     
     */
    public UnitType getInstitution() {
        return institution;
    }

    /**
     * Sets the value of the institution property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType }
     *     
     */
    public void setInstitution(UnitType value) {
        this.institution = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType }
     *     
     */
    public UnitType getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType }
     *     
     */
    public void setDepartment(UnitType value) {
        this.department = value;
    }

    /**
     * Gets the value of the userRights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userRights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserRights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserRightsType }
     * 
     * 
     */
    public List<UserRightsType> getUserRights() {
        if (userRights == null) {
            userRights = new ArrayList<UserRightsType>();
        }
        return this.userRights;
    }

    /**
     * Gets the value of the ssoAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SsoAttributesType }
     *     
     */
    public SsoAttributesType getSsoAttributes() {
        return ssoAttributes;
    }

    /**
     * Sets the value of the ssoAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SsoAttributesType }
     *     
     */
    public void setSsoAttributes(SsoAttributesType value) {
        this.ssoAttributes = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the resetCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResetCode() {
        return resetCode;
    }

    /**
     * Sets the value of the resetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResetCode(String value) {
        this.resetCode = value;
    }

    /**
     * Gets the value of the passPhrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassPhrase() {
        return passPhrase;
    }

    /**
     * Sets the value of the passPhrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassPhrase(String value) {
        this.passPhrase = value;
    }

    /**
     * Gets the value of the userType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserType() {
        return userType;
    }

    /**
     * Sets the value of the userType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserType(String value) {
        this.userType = value;
    }

    /**
     * Gets the value of the tokens property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tokens property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTokens().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserTokens }
     * 
     * 
     */
    public List<UserTokens> getTokens() {
        if (tokens == null) {
            tokens = new ArrayList<UserTokens>();
        }
        return this.tokens;
    }
    public String getLastVisit() {
        return lastVisit;
    }

    public void setLastVisit(String lastVisit) {
        this.lastVisit = lastVisit;
    }

}
