//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 11:02:19 AM EEST 
//


package org.opendelos.legacydomain.dlmuser;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gunet.opendelos.schemas.domain.dlmuser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gunet.opendelos.schemas.domain.dlmuser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DlmUser }
     * 
     */
    public DlmUser createDlmUser() {
        return new DlmUser();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link UserRightsType }
     * 
     */
    public UserRightsType createUserRightsType() {
        return new UserRightsType();
    }

    /**
     * Create an instance of {@link SsoAttributesType }
     * 
     */
    public SsoAttributesType createSsoAttributesType() {
        return new SsoAttributesType();
    }

    /**
     * Create an instance of {@link UserTokens }
     * 
     */
    public UserTokens createUserTokens() {
        return new UserTokens();
    }

}
