//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 11:02:19 AM EEST 
//


package org.opendelos.legacydomain.dlmuser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SsoAttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SsoAttributesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="edupersonprimaryorgunitdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="edupersonprimaryaffiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="givenname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="edupersonorgdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="edupersonaffiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title-lang-el" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="edupersonorgunitdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="givenname-lang-el" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cn-lang-el" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sn-lang-el" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SsoAttributesType", propOrder = {
    "uid",
    "mail",
    "sn",
    "edupersonprimaryorgunitdn",
    "edupersonprimaryaffiliation",
    "givenname",
    "edupersonorgdn",
    "edupersonaffiliation",
    "title",
    "cn",
    "titleLangEl",
    "edupersonorgunitdn",
    "givennameLangEl",
    "dn",
    "cnLangEl",
    "snLangEl"
})
public class SsoAttributesType {

    protected String uid;
    protected String mail;
    protected String sn;
    protected String edupersonprimaryorgunitdn;
    protected String edupersonprimaryaffiliation;
    protected String givenname;
    protected String edupersonorgdn;
    protected String edupersonaffiliation;
    protected String title;
    protected String cn;
    @XmlElement(name = "title-lang-el")
    protected String titleLangEl;
    protected String edupersonorgunitdn;
    @XmlElement(name = "givenname-lang-el")
    protected String givennameLangEl;
    protected String dn;
    @XmlElement(name = "cn-lang-el")
    protected String cnLangEl;
    @XmlElement(name = "sn-lang-el")
    protected String snLangEl;

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the sn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSn() {
        return sn;
    }

    /**
     * Sets the value of the sn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSn(String value) {
        this.sn = value;
    }

    /**
     * Gets the value of the edupersonprimaryorgunitdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdupersonprimaryorgunitdn() {
        return edupersonprimaryorgunitdn;
    }

    /**
     * Sets the value of the edupersonprimaryorgunitdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdupersonprimaryorgunitdn(String value) {
        this.edupersonprimaryorgunitdn = value;
    }

    /**
     * Gets the value of the edupersonprimaryaffiliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdupersonprimaryaffiliation() {
        return edupersonprimaryaffiliation;
    }

    /**
     * Sets the value of the edupersonprimaryaffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdupersonprimaryaffiliation(String value) {
        this.edupersonprimaryaffiliation = value;
    }

    /**
     * Gets the value of the givenname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenname() {
        return givenname;
    }

    /**
     * Sets the value of the givenname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenname(String value) {
        this.givenname = value;
    }

    /**
     * Gets the value of the edupersonorgdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdupersonorgdn() {
        return edupersonorgdn;
    }

    /**
     * Sets the value of the edupersonorgdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdupersonorgdn(String value) {
        this.edupersonorgdn = value;
    }

    /**
     * Gets the value of the edupersonaffiliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdupersonaffiliation() {
        return edupersonaffiliation;
    }

    /**
     * Sets the value of the edupersonaffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdupersonaffiliation(String value) {
        this.edupersonaffiliation = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the cn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCn() {
        return cn;
    }

    /**
     * Sets the value of the cn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCn(String value) {
        this.cn = value;
    }

    /**
     * Gets the value of the titleLangEl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleLangEl() {
        return titleLangEl;
    }

    /**
     * Sets the value of the titleLangEl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleLangEl(String value) {
        this.titleLangEl = value;
    }

    /**
     * Gets the value of the edupersonorgunitdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdupersonorgunitdn() {
        return edupersonorgunitdn;
    }

    /**
     * Sets the value of the edupersonorgunitdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdupersonorgunitdn(String value) {
        this.edupersonorgunitdn = value;
    }

    /**
     * Gets the value of the givennameLangEl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivennameLangEl() {
        return givennameLangEl;
    }

    /**
     * Sets the value of the givennameLangEl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivennameLangEl(String value) {
        this.givennameLangEl = value;
    }

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDn() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDn(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the cnLangEl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnLangEl() {
        return cnLangEl;
    }

    /**
     * Sets the value of the cnLangEl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnLangEl(String value) {
        this.cnLangEl = value;
    }

    /**
     * Gets the value of the snLangEl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnLangEl() {
        return snLangEl;
    }

    /**
     * Sets the value of the snLangEl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnLangEl(String value) {
        this.snLangEl = value;
    }

}
