//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 11:02:19 AM EEST 
//


package org.opendelos.legacydomain.dlmuser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserRightsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserRightsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Role" type="{http://gunet.gr/DlmUser}RoleType"/>
 *         &lt;element name="Scope" type="{http://gunet.gr/DlmUser}UnitType" minOccurs="0"/>
 *         &lt;element name="Cscope" type="{http://gunet.gr/DlmUser}UnitType" minOccurs="0"/>
 *         &lt;element name="ContentManager" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DataManager" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Scheduler" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserRightsType", propOrder = {
    "role",
    "scope",
    "cscope",
    "contentManager",
    "dataManager",
    "scheduler"
})
public class UserRightsType  implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3983645529876777522L;
	@XmlElement(name = "Role", required = true)
    protected RoleType role;
    @XmlElement(name = "Scope")
    protected UnitType scope;
    @XmlElement(name = "Cscope")
    protected UnitType cscope;
    @XmlElement(name = "ContentManager")
    protected Boolean contentManager;
    @XmlElement(name = "DataManager")
    protected Boolean dataManager;
    @XmlElement(name = "Scheduler")
    protected Boolean scheduler;

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setRole(RoleType value) {
        this.role = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType }
     *     
     */
    public UnitType getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType }
     *     
     */
    public void setScope(UnitType value) {
        this.scope = value;
    }

    /**
     * Gets the value of the cscope property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType }
     *     
     */
    public UnitType getCscope() {
        return cscope;
    }

    /**
     * Sets the value of the cscope property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType }
     *     
     */
    public void setCscope(UnitType value) {
        this.cscope = value;
    }

    /**
     * Gets the value of the contentManager property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContentManager() {
        return contentManager;
    }

    /**
     * Sets the value of the contentManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContentManager(Boolean value) {
        this.contentManager = value;
    }

    /**
     * Gets the value of the dataManager property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDataManager() {
        return dataManager;
    }

    /**
     * Sets the value of the dataManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDataManager(Boolean value) {
        this.dataManager = value;
    }

    /**
     * Gets the value of the scheduler property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScheduler() {
        return scheduler;
    }

    /**
     * Sets the value of the scheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScheduler(Boolean value) {
        this.scheduler = value;
    }

}
