//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 10:49:25 AM EET 
//


package org.opendelos.legacydomain.calendar;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://gunet.gr/AcademicCalendarSe}Periods"/>
 *         &lt;element ref="{http://gunet.gr/AcademicCalendarSe}Argies" minOccurs="0"/>
 *         &lt;element name="Studies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://gunet.gr/AcademicCalendarSe}Study" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "periods",
    "argies",
    "studies"
})
@XmlRootElement(name = "Department")
public class Department implements Serializable {

    @XmlElement(name = "Periods", required = true)
    protected Periods periods;
    @XmlElement(name = "Argies")
    protected Argies argies;
    @XmlElement(name = "Studies", required = true)
    protected Studies studies;


    public Periods getPeriods() {
        return periods;
    }


    public void setPeriods(Periods value) {
        this.periods = value;
    }


    public Argies getArgies() {
        return argies;
    }

    public void setArgies(Argies value) {
        this.argies = value;
    }

    /**
     * Gets the value of the studies property.
     * 
     * @return
     *     possible object is
     *     {@link Studies }
     *     
     */
    public Studies getStudies() {
        if (studies == null) {
            studies = new Studies();
        }
        return studies;
    }

    /**
     * Sets the value of the studies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Studies }
     *     
     */
    public void setStudies(Studies value) {
        this.studies = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://gunet.gr/AcademicCalendarSe}Study" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "study"
    })
    public static class Studies implements Serializable {

        @XmlElement(name = "Study")
        protected List<Study> study;

        /**
         * Gets the value of the study property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the study property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStudy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Study }
         * 
         * 
         */
        public List<Study> getStudy() {
            if (study == null) {
                study = new ArrayList<Study>();
            }
            return this.study;
        }

    }

}
