//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 10:49:25 AM EET 
//


package org.opendelos.legacydomain.calendar;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gunet.dilosopen.se.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RefId_QNAME = new QName("http://gunet.gr/AcademicCalendarSe", "RefId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gunet.dilosopen.se.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Institution }
     * 
     */
    public Institution createInstitution() {
        return new Institution();
    }

    /**
     * Create an instance of {@link Department }
     * 
     */
    public Department createDepartment() {
        return new Department();
    }

  
    public Argies createArgies() {
        return new Argies();
    }

    /**
     * Create an instance of {@link Argia }
     * 
     */
    public Argia createArgia() {
        return new Argia();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link Study }
     * 
     */
    public Study createStudy() {
        return new Study();
    }

    /**
     * Create an instance of {@link Periods }
     * 
     */
    public Periods createPeriods() {
        return new Periods();
    }

    /**
     * Create an instance of {@link AcademicCalendarSe }
     * 
     */
    public AcademicCalendarSe createAcademicCalendarSe() {
        return new AcademicCalendarSe();
    }

    /**
     * Create an instance of {@link Institution.Departments }
     * 
     */
    public Institution.Departments createInstitutionDepartments() {
        return new Institution.Departments();
    }

    /**
     * Create an instance of {@link Department.Studies }
     * 
     */
    public Department.Studies createDepartmentStudies() {
        return new Department.Studies();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gunet.gr/AcademicCalendarSe", name = "RefId")
    public JAXBElement<String> createRefId(String value) {
        return new JAXBElement<String>(_RefId_QNAME, String.class, null, value);
    }

}
