//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:43:55 AM EET 
//
/**
 * Implementation of Slides XSD Schema
 * <p>
 * @author openDelos Team
 * @since 0.1
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://gunet.gr/Slides")
package org.opendelos.legacydomain.slides;
