//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 01:38:03 PM EEST 
//


package org.opendelos.legacydomain.query;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FieldType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Title"/>
 *     &lt;enumeration value="EditorId"/>
 *     &lt;enumeration value="EditorName"/>
 *     &lt;enumeration value="CreatorId"/>
 *     &lt;enumeration value="CreatorName"/>
 *     &lt;enumeration value="SpeakerId"/>
 *     &lt;enumeration value="SpeakerName"/>
 *     &lt;enumeration value="Subject"/>
 *     &lt;enumeration value="Publisher"/>
 *     &lt;enumeration value="Department"/>
 *     &lt;enumeration value="Category"/>
 *     &lt;enumeration value="Language"/>
 *     &lt;enumeration value="Year"/>
 *     &lt;enumeration value="Room"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FieldType")
@XmlEnum
public enum FieldType {

    Title,
    EditorId,
    EditorName,
    CreatorId,
    CreatorName,
    SpeakerId,
    SpeakerName,
    Subject,
    Publisher,
    Department,
    Category,
    Language,
    Year,
    Room,
    Other;

    public String value() {
        return name();
    }

    public static FieldType fromValue(String v) {
        return valueOf(v);
    }

}
