//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 01:38:03 PM EEST 
//


package org.opendelos.legacydomain.query;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gunet.dilosdlm.schemas.query package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gunet.dilosdlm.schemas.query
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link FilterResultsType }
     * 
     */
    public FilterResultsType createFilterResultsType() {
        return new FilterResultsType();
    }

    /**
     * Create an instance of {@link SearchCourseType }
     * 
     */
    public SearchCourseType createSearchCourseType() {
        return new SearchCourseType();
    }

    /**
     * Create an instance of {@link SearchEventType }
     * 
     */
    public SearchEventType createSearchEventType() {
        return new SearchEventType();
    }

    /**
     * Create an instance of {@link DateFilterType }
     * 
     */
    public DateFilterType createDateFilterType() {
        return new DateFilterType();
    }

}
