//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 10:35:33 AM EEST 
//


package org.opendelos.model.security;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class TokenInfo {

    protected String domainName;
    protected String sharedSecret;
    protected String redirect_url;
    protected String userId;
    protected String rId;
    protected String token;
    protected String access;

}
