//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 04:30:01 PM EET 
//
/**
 * Implementation of xCourse XSD Schema
 * <p>
 * @author openDelos Team
 * @since 0.1
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://gunet.gr/xCourse", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opendelos.legacydomain.xcourse;
